### ISSUE TITLE
Just saying hello

### ISSUE THREAD

**Issue by bfeist** [HENDRIX-ZT2/pyrespeeder#1] opened 2018-01-28 18:15 UTC
Thanks so much for your efforts on this. You appear to have written just the software I need for quite a hairy flutter issue within newly digitized NASA Apollo archival recordings. I'd like to discuss in more detail. Please contact me at bf@benfeist.com if you're interested.

**Comment by HENDRIX-ZT2** [comment] 2018-01-29 19:52
Hi there!
I hope you find it useful. Mind you it is very early in development, so documentation is sparse at best and it is not thoroughly tested. I currently can't give you much direct support (uni exams phase!), but feel free to raise an issue if you encounter problems.

Processing the whole NASA archive is clearly not feasible at the moment, but you can produce good results for your selections. A lot depends on the source recording - if you have a hum or even better hiss/beep frequency that was picked up during the recording, it will make work much faster and more accurate. The originally constant frequency will now reveal the flutter distortion clearly, so you just have to trace it. If you have no such "shortcuts" in your recordings, the process becomes tricky, but not impossible.

**Comment by bfeist** [comment] 2018-01-30 14:01
Thanks for the response. I have written up a description of a potential process that I would like to bounce off you. Is there an email address I could reach you at? Essentially, I need to deflutter 30 track tapes. Track 1 contains an ERIG timecode that is fluttered. The tones on this track provide very strong traces of the flutter. Your software technique looks promising in now to trace the flutter adjustment necessary for track 1, and I could apply the same adjustment to the parallel tracks (2-30) to correct those as well. I've attached a picture of the flutter on a clip of track 1. 
![timecode track flutter fft](https://user-images.githubusercontent.com/662952/35570073-15e6a672-059c-11e8-9cf9-e740dea09fd9.png)

**Comment by HENDRIX-ZT2** [comment] 2018-01-30 14:23
Ahh, beautiful timecode - this should make tracing very easy! It also seems regular enough for you to try sine regression on it. Yes, you can use the flutter curve from track one for all tracks (assuming they were all captured in one run). The UI was not costructed with 30 tracks in mind, so you'll be getting some stretching when you load the file as is. I'll try to pack the channel selection into a scrollbox to avoid that. Sent you a mail as well.

**Comment by HENDRIX-ZT2** [comment] 2018-06-17 09:55
Gonna close this now since it is essentially resolved. :)

**Closed by HENDRIX-ZT2** 2018-06-17 09:55 UTC
